# Проверенные рабочие RSS-источники датских медиа (расширённая версия)
feeds:

  - url: https://www.dr.dk/nyheder/service/feeds/allenyheder
    name: DR Nyheder
    lang: da
    priority: 100
    active: true
    categories: [denmark, main, ukraine, visas, technology, integration]

  - url: https://ekstrabladet.dk/rssfeed/nyheder/
    name: Ekstra Bladet - Nyheder
    lang: da
    priority: 40
    active: true
    categories: [denmark, main, ukraine, visas, technology]

  - url: https://cphpost.dk/?feed=rss2
    name: The Copenhagen Post (English)
    lang: en
    priority: 30
    active: true
    categories: [denmark, ukraine, visas, technology, integration, immigration, main]
