# Скрипт для GitHub Actions (будет доработан позже)
name: DKNews Bot

on:
  schedule:
    - cron: '0 8 * * *'  # 08:00 UTC (10:00 Киев)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Download dependencies
        run: go mod download
      - name: Run bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: go run ./cmd/dknews/main.go
