name: Daily Danish News Bot

on:
  schedule:
    # Запуск каждый день в 08:00 UTC (09:00 CET / 10:00 CEST)
    - cron: '0 8 * * *'
  workflow_dispatch: # Позволяет запускать вручную для тестирования

jobs:
  send-news:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Download dependencies
      run: go mod download

    - name: Run news bot
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: go run cmd/dknews/main.go
